l_english:
 setting_very_low_ai_aggression:0 "Very Low Aggression"
 setting_very_low_ai_aggression_desc:0 "AI countries start significantly fewer diplomatic games and are significantly less inclined to conquer territories."
 setting_very_high_ai_aggression:0 "Very High Aggression"
 setting_very_high_ai_aggression_desc:0 "AI countries start diplomacy games significantly more often and tend to conquer territories significantly more often."

 setting_none_ai_aggression:0 "None Aggression"
 setting_none_ai_aggression_desc:0 "AI countries will not start diplomacy games or territories. Exception: Scripted diplomacy games."
 
 rule_autobuild_expansive_threshold:0 "Better Victoria 3 - Autobuild: Expensiv Threshold"
 setting_low_autobuild_expansive_threshold:0 "120%"
 setting_low_autobuild_expansive_threshold_desc:0 "Incoming [Concept('concept_good', 'goods')] may not be more expensive than 120% of the [Concept('concept_market_price', 'base price')]."
 setting_standard_autobuild_expansive_threshold:0 "Recommended: 135%"
 setting_standard_autobuild_expansive_threshold_desc:0 "Incoming [Concept('concept_good', 'goods')] may not be more expensive than 135% of the [Concept('concept_market_price', 'base price')]."
 setting_high_autobuild_expansive_threshold:0 "150%"
 setting_high_autobuild_expansive_threshold_desc:0 "Incoming [Concept('concept_good', 'goods')] may not be more expensive than 150% of the [Concept('concept_market_price', 'base price')]."
 
 rule_autobuild_cheap_threshold:0 "Better Victoria 3 - Autobuild: Cheap Threshold"
 setting_low_autobuild_cheap_threshold:0 "80%"
 setting_low_autobuild_cheap_threshold_desc:0 "Output [Concept('concept_good', 'goods')] may not be cheaper than 80% of the [Concept('concept_market_price', 'base price')]."
 setting_standard_autobuild_cheap_threshold:0 "Recommended: 65%"
 setting_standard_autobuild_cheap_threshold_desc:0 "Output [Concept('concept_good', 'goods')] may not be cheaper than 65% of the [Concept('concept_market_price', 'base price')]."
 setting_high_autobuild_cheap_threshold:0 "50%"
 setting_high_autobuild_cheap_threshold_desc:0 "Output [Concept('concept_good', 'goods')] may not be cheaper than 50% of the [Concept('concept_market_price', 'base price')]."
 
  rule_autobuild_markt_access_threshold:0 "Better Victoria 3 - Autobuild: [Concept('concept_market_access', 'Markt-Access')] Threshold"
 setting_low_autobuild_markt_access_threshold:0 "80%"
 setting_low_autobuild_markt_access_threshold_desc:0 "The [Concept('concept_state', 'Province')] needs at least 80% [Concept('concept_market_access', 'market access')]."
 setting_standard_autobuild_markt_access_threshold:0 "90%"
 setting_standard_autobuild_markt_access_threshold_desc:0 "The [Concept('concept_state', 'Province')] needs at least 90% [Concept('concept_market_access', 'market access')]."
 setting_high_autobuild_markt_access_threshold:0 "Recommended: 95%"
 setting_high_autobuild_markt_access_threshold_desc:0 "The [Concept('concept_state', 'Province')] needs at least 95% [Concept('concept_market_access', 'market access')]."
 
 rule_autobuild_cash_ratio_threshold:0 "Better Victoria 3 - Autobuild: Building Cash-Ratio Threshold"
 setting_low_autobuild_cash_ratio_threshold:0 "25%"
 setting_low_autobuild_cash_ratio_threshold_desc:0 "The [Concept('concept_cash_reserves', 'reserve')] of [Concept('concept_building', 'buildings')] must be at least 25%. "
 setting_standard_autobuild_cash_ratio_threshold:0 "Recommended: 50%"
 setting_standard_autobuild_cash_ratio_threshold_desc:0 "The [Concept('concept_cash_reserves', 'reserve')] of [Concept('concept_building', 'buildings')] must be at least 50%. "
 setting_high_autobuild_cash_ratio_threshold:0 "75%"
 setting_high_autobuild_cash_ratio_threshold_desc:0 "The [Concept('concept_cash_reserves', 'reserve')] of [Concept('concept_building', 'buildings')] must be at least 75%. "
 
 rule_trade_center_infrastructure_usages:0 "Better Victoria 3 - Trade center: Infrastructure usages"
 setting_none_trade_center_infrastructure_usages:0 "None"
 setting_none_trade_center_infrastructure_usages_desc:0 "Trade center using none infrastructure."
 setting_low_trade_center_infrastructure_usages:0 "50%"
 setting_low_trade_center_infrastructure_usages_desc:0 "Trade center using -50% infrastructure."
 setting_default_trade_center_infrastructure_usages:0 "Recommended: Vanilla"
 setting_default_trade_center_infrastructure_usages_desc:0 "Not changes."