l_german:
 setting_very_low_ai_aggression:0 "Very Low Aggression"
 setting_very_low_ai_aggression_desc:0 "KI-Länder beginnen deutlich weniger Diplomatiespiele und neigen deutlich weniger dazu, Territorien zu erobern."
 setting_very_high_ai_aggression:0 "Very High Aggression"
 setting_very_high_ai_aggression_desc:0 "KI-Länder beginnen deutlich häufiger Diplomatiespiele und neigen deutlich häufiger dazu, Territorien zu erobern."

 setting_none_ai_aggression:0 "Keine Aggression"
 setting_none_ai_aggression_desc:0 "KI-Länder werden keine Diplomatiespiele starten oder Territorien. Ausnahme: Gescripte Diplomatiespiele spiele."
 
 rule_autobuild_expansive_threshold:0 "Better Victoria 3 - Autobuild: Expensiv Threshold"
 setting_low_autobuild_expansive_threshold:0 "120%"
 setting_low_autobuild_expansive_threshold_desc:0 "[Concept('concept_good', 'Eingangswaren')] dürfen nicht teurer als 120% des [Concept('concept_market_price', 'Grundpreises')] sein."
 setting_standard_autobuild_expansive_threshold:0 "Empfohlen: 135%"
 setting_standard_autobuild_expansive_threshold_desc:0 "[Concept('concept_good', 'Eingangswaren')] dürfen nicht teurer als 135% des [Concept('concept_market_price', 'Grundpreises')] sein."
 setting_high_autobuild_expansive_threshold:0 "150%"
 setting_high_autobuild_expansive_threshold_desc:0 "[Concept('concept_good', 'Eingangswaren')] dürfen nicht teurer als 150% des [Concept('concept_market_price', 'Grundpreises')] sein."
 
 rule_autobuild_cheap_threshold:0 "Better Victoria 3 - Autobuild: Cheap Threshold"
 setting_low_autobuild_cheap_threshold:0 "80%"
 setting_low_autobuild_cheap_threshold_desc:0 "[Concept('concept_good', 'Ausgangswaren')] dürfen nicht billiger als 80% des [Concept('concept_market_price', 'Grundpreises')] sein."
 setting_standard_autobuild_cheap_threshold:0 "Empfohlen: 65%"
 setting_standard_autobuild_cheap_threshold_desc:0 "[Concept('concept_good', 'Ausgangswaren')] dürfen nicht billiger als 65% des [Concept('concept_market_price', 'Grundpreises')] sein."
 setting_high_autobuild_cheap_threshold:0 "50%"
 setting_high_autobuild_cheap_threshold_desc:0 "[Concept('concept_good', 'Ausgangswaren')] dürfen nicht billiger als 50% des [Concept('concept_market_price', 'Grundpreises')] sein."
 
 rule_autobuild_markt_access_threshold:0 "Better Victoria 3 - Autobuild: Markt-Access Threshold"
 setting_low_autobuild_markt_access_threshold:0 "80%"
 setting_low_autobuild_markt_access_threshold_desc:0 "Die [Concept('concept_state', 'Provinz')] braucht mindestens eine [Concept('concept_market_access', 'Marktzugang')] von 80%."
 setting_standard_autobuild_markt_access_threshold:0 "90%"
 setting_standard_autobuild_markt_access_threshold_desc:0 "Die [Concept('concept_state', 'Provinz')] braucht mindestens eine [Concept('concept_market_access', 'Marktzugang')] von 90%."
 setting_high_autobuild_markt_access_threshold:0 "Empfohlen: 95%"
 setting_high_autobuild_markt_access_threshold_desc:0 "Die [Concept('concept_state', 'Provinz')] braucht mindestens eine [Concept('concept_market_access', 'Marktzugang')] von 95%."
 
 rule_autobuild_cash_ratio_threshold:0 "Better Victoria 3 - Autobuild: Building Cash-Ratio Threshold"
 setting_low_autobuild_cash_ratio_threshold:0 "25%"
 setting_low_autobuild_cash_ratio_threshold_desc:0 "Die [Concept('concept_cash_reserves', 'Rücklagen')] von [Concept('concept_building', 'Gebäuden')] muss mindestens 25% betragen."
 setting_standard_autobuild_cash_ratio_threshold:0 "Empfohlen: 50%"
 setting_standard_autobuild_cash_ratio_threshold_desc:0 "Die [Concept('concept_cash_reserves', 'Rücklagen')] von [Concept('concept_building', 'Gebäuden')] muss mindestens 50% betragen."
 setting_high_autobuild_cash_ratio_threshold:0 "75%"
 setting_high_autobuild_cash_ratio_threshold_desc:0 "Die [Concept('concept_cash_reserves', 'Rücklagen')] von [Concept('concept_building', 'Gebäuden')] muss mindestens 75% betragen."
 
  rule_trade_center_infrastructure_usages:0 "Better Victoria 3 - Trade center: Infrastructure usages"
 setting_none_trade_center_infrastructure_usages:0 "None"
 setting_none_trade_center_infrastructure_usages_desc:0 "Trade center nutzt keine Infrastruktur."
 setting_low_trade_center_infrastructure_usages:0 "50%"
 setting_low_trade_center_infrastructure_usages_desc:0 "Trade center benutzt nur 50% der Infrastruktur des Vanilla wertes."
 setting_default_trade_center_infrastructure_usages:0 "Recommended: Vanilla"
 setting_default_trade_center_infrastructure_usages_desc:0 "Not changes."
